name: Docs build
on:
  push:
    branches: [main]
    paths:
      - "docs/**"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run npm install
        run: npm ci

      - name: Check formatting
        run: npm run format

      - name: Run build
        run: npm run build

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: docs-build-output
          path: docs/build/
          retention-days: 1
